# Generated by Django 2.1.2 on 2018-11-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.TextField(default='', verbose_name='摘要'),
        ),
    ]
